# Generated by Django 3.1.7 on 2021-03-28 00:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turma', models.CharField(max_length=20)),
                ('codigo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.CharField(max_length=10)),
            ],
        ),
         migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('cpf', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('contato', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='SistemaEscolar.pessoa')),
                ('nascimento', models.DateField(blank=True, null=True)),
            ],
            bases=('SistemaEscolar.pessoa',),
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='SistemaEscolar.pessoa')),
                ('salario', models.FloatField(blank=True, max_length=20, null=True)),
            ],
            bases=('SistemaEscolar.pessoa',),
        ),
       
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=10)),
                ('uf', models.CharField(max_length=2)),
                ('cidade', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=20)),
                ('numero', models.CharField(max_length=10)),
                ('rua', models.CharField(max_length=20)),
                ('pessoa', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SistemaEscolar.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('matricula', models.CharField(max_length=20)),
                ('anexos', models.FileField(blank=True, null=True, upload_to='SistemaEscolar/doc')),
                ('observacao', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('turma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SistemaEscolar.turma')),
                ('turno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SistemaEscolar.turno')),
                ('aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SistemaEscolar.aluno')),
            ],
        ),
    ]
