# Generated by Django 3.1.7 on 2021-03-30 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SistemaEscolar', '0003_observacao_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='data',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='status',
            field=models.CharField(default='PENDENTE', max_length=20),
        ),
    ]
