# Generated by Django 3.1.7 on 2021-03-31 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SistemaEscolar', '0004_auto_20210330_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'PENDENTE'), ('CONCLUÍDA', 'CONCLUÍDA'), ('CANCELADA', 'CANCELADA'), ('RECUSADA', 'RECUSADA')], default='PENDENTE', max_length=20),
        ),
    ]
