# Generated by Django 3.1.7 on 2021-04-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SistemaEscolar', '0009_auto_20210401_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='data_contratacao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
